<a href="https://colab.research.google.com/github/DmitriyRy/Lessons/blob/main/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Удаление данных из DataFrame

In [8]:
import pandas as pd
df=pd.DataFrame({'x':[1,3,2], 'y':[2,4,1]})

In [2]:
df

   x  y
0  1  2
1  3  4
2  2  1

In [9]:
# Удаление произвольной строки
# (индекс строки, axis=0 - строка удаляется по вертикальной оси, вдоль индексов)
# inplace=True - изменения применяются к исходному DataFrame.
df.drop(1,axis=0,inplace=True)

In [10]:
df

   x  y
0  1  2
2  2  1

In [ ]:
# Удаление столбцов
# 'x' - название удаляемого столбца
# axis=1 - удаляется столбец
df.drop('x',axis=1)

In [5]:
# другой способ
# 'x' - название удаляемого столбца
del df['x']

In [6]:
df

   y
0  2
2  1

Переиндексация
с помощью reset_index() с параметром drop=True

In [11]:
df=pd.DataFrame({'x':[1,3,2], 'y':[2,4,1]})
df.drop(1,axis=0,inplace=True)
df.reset_index(drop=True)

   x  y
0  1  2
1  2  1

Сравнение датафреймов

In [14]:
df1=pd.DataFrame({'x':[1,3,2],'y':[2,4,1]})
df2=pd.DataFrame({'x':[3,1,2],'y':[0,2,2]})
print(df1)
print(df2)
# выводим в ячейках новой таблицы True если ячейки в массиве 1 >= ячейкам во втором
print(df1>=df2)

   x  y
0  1  2
1  3  4
2  2  1
   x  y
0  3  0
1  1  2
2  2  2
       x      y
0  False   True
1   True   True
2   True  False

In [15]:
# можно указать несколько условий при сравнении
# используются символы & (и), | (или)

# выведем те значения df1, которые больше 1
df1[df1>1]

     x    y
0  NaN  2.0
1  3.0  4.0
2  2.0  NaN

In [20]:
# выведем те значения df2, которые удовлетворяют двум условиям
df2[(df2<2)&(df2>0)]

     x   y
0  NaN NaN
1  1.0 NaN
2  NaN NaN

In [19]:
# выведем те значения df2, которые удовлетворяют одному из двух условий
df2[(df2<1)|(df2>2)]

     x    y
0  3.0  0.0
1  NaN  NaN
2  NaN  NaN

Поиск пустых ячеек

In [21]:
# два метода .isna() и .isnull()
data={'Имя': ['Анна','Борис',None, 'Джон'], 'Возраст':[25,30,28,None]}
df=pd.DataFrame(data)

In [22]:
df

     Имя  Возраст
0   Анна     25.0
1  Борис     30.0
2   None     28.0
3   Джон      NaN

In [31]:
print (df.isnull())

     Имя  Возраст
0  False    False
1  False    False
2   True    False
3  False     True

In [35]:
# для фильтрации строк можно использовать функцию .loc
x=df.isnull()
df.isnull().loc[x['Имя'] == True]

    Имя  Возраст
2  True    False

Действия с DataFrame

In [ ]:
# .sum() - сложение данных в столбце датафрейма
df['column_name'].sum()
# .mean() - расчет среднего значения
df['column_name'].mean()
# .median() - медиана по столбцу
df['column_name'].median()
# .std() - стандартное отклонение
df['column_name'].std()
# пропуски данных (NaN) - игнорируются!

In [ ]:
# .unique() - позволяет определить количество уникальных значений (в столбце или датафрейме)
df['Название столбца'].unique

In [36]:
data={'Цвет':['Красный','Синий','Зеленый','Красный','Желтый','Зеленый']}
df=pd.DataFrame(data)
# Получаем уникальные значения в столбце "Цвет"
unique_colors=df['Цвет'].unique()

In [37]:
unique_colors

array(['Красный', 'Синий', 'Зеленый', 'Желтый'], dtype=object)

Расчет корреляции - метод .corr()
- между всеми парами столбцов или двумя конкретными столбцами. Выводит значение от минус 1 до 1, возвращает матрицу корреляции

In [38]:
df2.corr()

          x         y
x  1.000000 -0.866025
y -0.866025  1.000000